CREATE TABLE login_code
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                      VARCHAR(64)  NOT NULL,
    member_id                 BIGINT       NOT NULL,
    is_new_member             BOOLEAN      NOT NULL,
    has_agreed_required_terms BOOLEAN      NOT NULL,
    active_team_id            BIGINT,
    expires_at                TIMESTAMP    NOT NULL,
    used                      BOOLEAN      NOT NULL,
    created_at                TIMESTAMP    NOT NULL
);

CREATE UNIQUE INDEX uk_login_code_code ON login_code (code);
