CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT,
    name VARCHAR(20),
    nickname VARCHAR(30),
    profile_img_url TEXT,
    social_provider VARCHAR(50) NOT NULL,
    provider_id TEXT,
    status VARCHAR(50) NOT NULL,
    terms_agreed BOOLEAN NOT NULL,
    privacy_agreed BOOLEAN NOT NULL,
    terms_agreed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    description TEXT,
    team_img_url TEXT,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE place (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    latitude NUMERIC(18, 10),
    longitude NUMERIC(18, 10),
    address TEXT,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT,
    date DATE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE team_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES team (id),
    member_id BIGINT NOT NULL REFERENCES member (id),
    nickname VARCHAR(30),
    profile_img_url TEXT,
    role VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE team_invite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES team (id),
    invite_token TEXT,
    expires_at TIMESTAMP NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE feed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_member_id BIGINT NOT NULL REFERENCES team_member (id),
    team_id BIGINT NOT NULL REFERENCES team (id),
    place_id BIGINT REFERENCES place (id),
    question_id BIGINT REFERENCES question (id),
    content TEXT,
    meeting_date DATE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE feed_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id BIGINT NOT NULL REFERENCES feed (id),
    team_member_id BIGINT NOT NULL REFERENCES team_member (id),
    content TEXT,
    position_x INTEGER NOT NULL,
    position_y INTEGER NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE feed_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id BIGINT NOT NULL REFERENCES feed (id),
    team_member_id BIGINT NOT NULL REFERENCES team_member (id)
);

CREATE TABLE feed_reaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id BIGINT NOT NULL REFERENCES feed (id),
    team_member_id BIGINT NOT NULL REFERENCES team_member (id),
    emoji TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_feed_reaction_feed_member UNIQUE (feed_id, team_member_id)
);

CREATE TABLE feed_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id BIGINT NOT NULL REFERENCES feed (id),
    img_url TEXT,
    order_index INTEGER NOT NULL,
    width INTEGER,
    height INTEGER,
    created_at TIMESTAMP NOT NULL
);
